### ISSUE TITLE
Disk access is excessive on node

### ISSUE THREAD

**Issue by kryztoval** [aeternity/epoch#1002]
## Expected Behavior
Normal read access of about 1 MB/s

## Actual Behavior
A lot of dis reads in excess of 110MB/s
...

## Steps to Reproduce the Problem

  1. Install Centos Latest
  2. Install Docker Latest
  3. Install Epoch image
  4. Run it
  
  
## Logs, error output, etc.
 
http://prntscr.com/j76zbd

## Specifications
  - Virtualization: Docker
  - Hardware specs: 
    * RAM: 1GB
    * CPU: 1 Xeon @ 2.0GBz
  - OS:  CentOS Linux release 7.4.1708
  - Node Version: docker image id 631ad653cb4a for docker.io/aeternity/epoch

**Comment by kryztoval** [comment]
The docker container rewrites the configuration file in /home/epoch/node every single time it is restarted, it copies the file from /home/epoch/node/docs/examples/epoch_testnet.yaml over it.

You can fix this by modifying the /home/epoch/node/docs/examples/epoch_testnet.yaml file with [this troubleshooting](https://github.com/aeternity/epoch/wiki/Troubleshooting#resolution)

Or by commenting the file that copies it in /docker-entrypoint.sh and changing the file in /home/epoch/node/epoch.yaml with  [this troubleshooting](https://github.com/aeternity/epoch/wiki/Troubleshooting#resolution)

This seems to solve the access issue (could be due to excessive amount of swapping).

**Comment by dincho** [comment]
> The docker container rewrites the configuration file in /home/epoch/node every single time it is restarted, it copies the file from /home/epoch/node/docs/examples/epoch_testnet.yaml over it.

@kryztoval you should create custom configuration file and point the `epoch` to it by using the `EPOCH_CONFIG` environment variable. There is an [example in the docs](https://github.com/aeternity/epoch/blob/master/docs/docker.md#changing-the-configuration-file)

> This seems to solve the access issue (could be due to excessive amount of swapping).

[The minimum required RAM](https://github.com/aeternity/epoch/blob/master/docs/operation.md#start-node) to run a mining node with the default (testnet) mean28 algorithm is 4GB. Indeed the lower (1GB) memory that you used might cause the hight I/O because of swapping.

Please retry with 4GB of memory, and let me know if the hight I/O issue persist so I can help further.

**Comment by dincho** [comment]
> It is working pretty good now.

Great, I assume I can close the issue now.
