### ISSUE TITLE
make prod-build

### ISSUE THREAD

**Issue by rootdoc** [aeternity/epoch#1444]
===> Linking _build/default/lib/base58 to _build/prod/lib/base58
===> Fetching cowboy ({git,"https://github.com/ninenines/cowboy.git",
{ref,
"8d49ae3dda5b4274e55d2f4e5a5b4da0515b5a10"}})
===> Failed to fetch and copy dep: {git,"https://github.com/ninenines/cowboy.git",
{ref,
"8d49ae3dda5b4274e55d2f4e5a5b4da0515b5a10"}}
Makefile:312: recipe for target 'internal-build' failed
make: *** [internal-build] Error 1

**Comment by rootdoc** [comment]
===> Linking _build/default/lib/base58 to _build/prod/lib/base58
===> Fetching cowboy ({git,"https://github.com/ninenines/cowboy.git",
                                 {ref,
                                     "8d49ae3dda5b4274e55d2f4e5a5b4da0515b5a10"}})
===> Failed to fetch and copy dep: {git,"https://github.com/ninenines/cowboy.git",
                                  {ref,
                                      "8d49ae3dda5b4274e55d2f4e5a5b4da0515b5a10"}}
Makefile:312: recipe for target 'internal-build' failed
make: *** [internal-build] Error 1

**Comment by ThomasArts** [comment]
The error above indicate that you may have a problem fetching a third party dependency. It might be because of github having trouble when you tried or due to a bad internet connection on your end.

You might want to verify that it is fetchable by just using `git clone https://github.com/ninenines/cowboy.git` in the linux shell.

If that still does not work, run
`DEBUG=1 rebar3 compile`
in the linux shell. This might give slightly more information on what goes wrong when fetching this package.

**Comment by evdoks** [comment]
Closing is resolved
