### ISSUE TITLE
How do you get the the basic info from the network?

### ISSUE THREAD

**Issue by kryztoval** [aeternity/epoch#1729]
## Expected Behavior
To see endpoints for
/accounts/{pubkey}/transactions
To get a list of all transactions numbers that have affected an address.

/network/status
To get the amount of coins in the network, number of online nodes, average fee, etc.

## Actual Behavior
No such endpoints exist

**Comment by kryztoval** [comment]
Not a fan of answering my own questions, but found more information here:
https://github.com/aeternity/epoch/pull/1224 https://www.pivotaltracker.com/n/projects/2124891/stories/158175735

So it seems the argument for not having /account/{pubkey/txs is because the database to get that working was broken and instead of fixing it the best solution was to remove it.

Well, under that same principle if I were to transverse the whole database and look at all the coins generated I would have to process all transactions in the database. I guess it makes sense to try and make the database as small as possible for the nodes. But the explorer does need it, and some other information in the network is useful. I know for example that BTC blockchain has the block reward, the tx with the destination for the reward, the total coins out besides some others.

I don't like this. but sure it is something that is not needed for core functionality, neither are seats in a car. But hey! Users love those.

I have to say that this leaves me with a question as to how is the transaction explorer in the blockchain explorer gonna be implemented? In ethereum mist wallet does this via a contract, in the etherscan explorer is done by the explorer itself, or the node it connects to.

But how are we in aeternity gonna present this information or allow the wallet/explorer to collect this data to calculate them on their own?

To get a complete list of transactions you need to know all the micro blocks, to get all the micro blocks you need to know the key blocks, to get all the key blocks you have to go from earch key block and see if any have micro blocks which usually have transactions (I don't really know if key blocks can have micro blocks without having a transaction... not so into the blockchain yet).

**Comment by gorillainduction** [comment]
Hi @kryztoval 

The reason for removing the index from account to transactions was because it was broken, but more importantly that we deemed the functionality too heavy for the core node.

The intention was (and I guess still is) to provide the information through a plugin application in the node (search for label:transaction-middleware in Pivotal) that can be enabled if the node operator wants to provide this service. However, we have been quite pressed for time, so that work has been pushed back in the backlog.

**Comment by kryztoval** [comment]
@gorillainduction Amazing, I can see the transaction-middleware is programmed! Those are happy news indeed.

How about the number of spent coins? or the total coins on the network? or the average fee? are those too programmed in a middleware?

**Comment by gorillainduction** [comment]
Those numbers are not planned as far as I know and I couldn't find anything in a quick search in the backlog.

I added https://www.pivotaltracker.com/story/show/161743897 to track this request.

Thanks for the suggestions @kryztoval

**Comment by evdoks** [comment]
@kryztoval, as @gorillainduction wrote, there is a number of tickets in [Pivotal Tracker](https://www.pivotaltracker.com/n/projects/2124891)  labeled with `transaction-middleware` and grouped under [Transaction History Middleware v1 epic](https://www.pivotaltracker.com/epic/show/4043125). The middleware is work in progress in we plan to release it shortly after the mainnet launch. Is there is anything else you would like to add? Otherwise I will close this issue and the progress can be tracked via Pivotal Tracker.

**Comment by kryztoval** [comment]
All my points have been addressed and the missing pivotal tracker tasks were created. thank you.
