### ISSUE TITLE
5 transactions dissappered

### ISSUE THREAD

**Issue by jdgcs** [aeternity/epoch#1945]

**Comment by jdgcs** [comment]
closed for public influence

**Comment by hanssv** [comment]
The issue was about transactions and microblocks that "disappeared". We had a look at the said transactions and they were indeed first included in one micro block, only to have this micro block ending up on a micro fork and being orphaned. The transactions then were placed in a micro block in the next generation. 

This will happen from time to time, and it is one of the negative side effects of the Bitcoin NG consensus with short time interval between micro blocks. I.e. this is expected behavior, but it can look confusing when you are not fully familiar with the consensus algorithm!

**Comment by jdgcs** [comment]
> The issue was about transactions and microblocks that "disappeared". We had a look at the said transactions and they were indeed first included in one micro block, only to have this micro block ending up on a micro fork and being orphaned. The transactions then were placed in a micro block in the next generation.
> 
> This will happen from time to time, and it is one of the negative side effects of the Bitcoin NG consensus with short time interval between micro blocks. I.e. this is expected behavior, but it can look confusing when you are not fully familiar with the consensus algorithm!

I see~that would be nice!

Thanks!
