### ISSUE TITLE
post transcation error: Invalid api encoding

### ISSUE THREAD

**Issue by guotie** [aeternity/epoch#1956]
## Expected Behavior

post API /v2/transcations failed

## Actual Behavior

success

## Steps to Reproduce the Problem

post the tx api:
```
curl -X POST "http://192.168.1.122:3013/v2/transactions" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"tx\": \"tx_77HAufwc2o474Dk39cz92mJZwWfThZYoAd3M7wka9KY7dWeeeBzxpYTwAB3iReJ5XAUKtyWS3YXdRsX3MDX1yUmck2ewFhwcVB7nWybnBtLwopyvGfh6gLxEk2oY4H2cF9Lv5ZwBVdgGjyYn4UdkeadFBv8fEbaaorFfbaqWMyD15ikQjC6jWZjk6aF4Erq57DfJT1d3s5coeck9ikD3aKHSXj3ZcHVo6ujevkRVBiwPauHPqkVBB\"}"
```

response:
```
{"reason":"Invalid api encoding"}
```

**Comment by noandrea** [comment]
I think the problem here is with the encoding of the transaction. For the Roma release the encoding for the transaction has been changed to base64 with checksum ([here](https://github.com/aeternity/protocol/blob/14db60b7db4d51618ebad539aaf6a0b40b72e633/epoch/api/api_encoding.md)).

this is the same transaction but encoded in base64:
`tx_+K0LAfhCuEBC1RqN/82fbwkMDFRfAIM8TbMrRZExosWiwQ2COhkqD6z+c9smrmrFPqO2W5kSnfrv4+WwXANpR3S0LjDJ2WUEuGX4YwwBoQEZSfC6lpjA3coVQ76+43LwY86L6TBhcQFcMh3xOD2Yr6EBL4SNMItRNjNretVJr40fLGgJQOksMEqmhCFeFzAfg++IRWORgkT0AACGvv5vZyAAgiwZiDDs5FY/7+oAgGelaLY=`

**Comment by guotie** [comment]
then, I change encoding to base64, I got 
```
 {"reason":"Invalid tx"}
```

**Comment by guotie** [comment]
It's my fault , I got the wrong nonce.
