### ISSUE TITLE
Investigate using LevelDB for storage

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#2]
Investigate using [LevelDB](http://leveldb.org/) or [RocksDB](http://rocksdb.org/) for transaction and block storage. 

We should try to use an existing storage layer as much as we can and avoid rolling a home-grown one.

[Exonum is using LevelDB](http://exonum.com/doc/get-started/design-overview/) and we should look into whether we should too. There's a [LevelDB API for Erlang](https://github.com/basho/eleveldb) that we can piggyback on.

**Comment by lucafavatella** [comment]
Wrt wanting to persist pending transactions, and using a key-value store for that, I noticed that:
* Each transaction is meant to have an account (pubkey) and a nonce related to it (they used to be fields 2 and 3 in all the old records);
* The transaction is valid only if the nonce in the transaction is strictly greater than the nonce in the account - see https://github.com/aeternity/testnet/blob/b53f5e1788a3c18651aab7acaa309eebd8929279/apps/ae_core/src/consensus/trees/accounts.erl#L46
* The nonce in the transaction is meant to become the new nonce in the account - see https://github.com/aeternity/testnet/blob/b53f5e1788a3c18651aab7acaa309eebd8929279/apps/ae_core/src/consensus/trees/accounts.erl#L54

This means that each transaction is meant to be identified by the couple pubkey-nonce in the transaction. If there are two pending transactions with the same pubkey and nonce, the node shall take the decision of which to keep as only one of the two can ever go in block.

**Comment by lucafavatella** [comment]
Today I performed basic investigation of using key-value store for transaction and block storage:
* Blocks can be stored by hash of the related block header;
  * For iteration, see block headers.
* Block headers, if they need to be stored as separate from blocks, can be stored by hash;
  * For iteration up to the genesis block, the previous hash enables traversal;
  * A potential optimization for iteration is enriching each stored block header with hash of earlier ancestors (see [1](https://github.com/aeternity/testnet/blob/b53f5e1788a3c18651aab7acaa309eebd8929279/apps/ae_core/src/consensus/chain/block.erl#L169) and [2](https://github.com/aeternity/testnet/blob/b53f5e1788a3c18651aab7acaa309eebd8929279/docs/todo.md)).
* The local view of the chain can be persisted as a single key e.g. "top" with value the hash of the block header identifying the chain;
  * No iteration applicable.
* Observed invalid block headers (potential optimization in order to avoid re-validating them) can be stored using as key the hash and as value e.g. "invalid";
  * No iteration applicable.
* Pending transactions (nice to have) can be stored by couple pubkey-nonce;
  * **Iteration requires further investigation**.
* The Merkle trees can be stored by storing each node by its hash - as per Ethereum's modified Merkle Patricia tree (see [1](https://github.com/ethereum/wiki/wiki/%5BEnglish%5D-Patricia-Tree) and [2](https://github.com/aeternity/testnet/wiki/Merkle-tree-implementation-alternatives#ethereum)).
  * Iteration requires a known root of Merkle tree - that is reasonable;
  * **Garbage collection requires further investigation**.

@wagerlabs @sennui

**Comment by lucafavatella** [comment]
In summary: we can use leveldb, but will need to pay attention to:
* Garbage collection of state trees;
* Iteration of pending transactions, following better understanding of how they are used.

Wrt trees garbage collection, I expect that by using leveldb we will have the same challenges as with any other key-value storage libraries.

**Comment by wagerlabs** [comment]
This is an [insightful thread](https://bitco.in/forum/threads/core-moving-from-leveldb-to-sqlite.145/). We should use RocksDB instead via the [Erlang bindings](https://github.com/leo-project/erocksdb).
