### ISSUE TITLE
Mine block using Cuckoo Cycle PoW

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#20]
Depends on 

- [ ] #5

**Comment by akorosmezey** [comment]
John Tromp suggests to use a graph size in the 2^28-2^32 range. The requirement of progress-freeness boils down to tuning the duration of a solution attempt significantly smaller than the block interval time. (Having solution times close to the block interval excludes lower-performance participants from the PoW competition, making it less egalitarian.) This favours smaller memory footprints. 
 On the other hand, the the Cuckoo Cycle algorithm is aiming at using more memory than that available on a single memory chip and also large enough to make the participation hard for botnets without excessive swapping.
 In order to make a reasonable compromise, John Tromp suggested to use graph sizes in the range of 2^28-2^32. 

 The default implementation of Cuckoo cycle (what we are currently using) is has graph size 2^28. This performs a single solution attempt in about 3 seconds in a MacBook Pro. The chance of finding a solution in a single step is 2.2%, so typically a solution requires a bit  more than 2 minutes. The chance of finding a solution is reduced by introducing a difficulty by requiring the SHA-256 hash of the found solution to be below a certain target threshold (like in SHA-256 PoW).   We need a much lighter difficulty than in the SHA-265 case as finding a Cuckoo Cycle solution is orders of magnitudes slower than calculating a hash.
 The size can be adjusted in compile-time by setting a parameter for the NIF code. We set the graph size 2^20 for unit tests, this reduces the memory footprint by a factor of 256 and the solution time about 30 milliseconds (not appropriate for production code).
