### ISSUE TITLE
Persist authenticated dynamic dictionaries

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#275]
We need to be able to store trees backing the authenticated dynamic dictionaries to disk in such a way that several versions of the tree can be kept around efficiently.

For example, we may start with tree A and insert a new account with a given balance. This will give us tree B which will need to keep around together with A. 

We then need to be able to discard tree B and _garbage-collect_ its data from disk storage such that only tree A is kept around.

**Comment by lucafavatella** [comment]
@wagerlabs @akorosmezey @happi @gorillainduction

Following chat with @wagerlabs yesterday I checked to which extent the [authenticated dynamic dictionaries](http://eprint.iacr.org/2016/994) [implementation](https://github.com/input-output-hk/scrypto/tree/2.0.3) handles versioned persistency, and I am summarizing what I found so far and my conclusions up to this point:
* The [API between persisted prover and storage](https://github.com/input-output-hk/scrypto/blob/2.0.3/src/main/scala/scorex/crypto/authds/avltree/batch/PersistentBatchAVLProver.scala#L25) enables keeping multiple versions of the tree, though it makes not straightforward keeping only *some* versions of the tree;
* The [`input-output-hk/scrypto`](https://github.com/input-output-hk/scrypto/tree/2.0.3) does not implement any *durable* storage.

My analysis follows.

The `PersistentBatchAVLProver` enriches the non-persisted prover `BatchAVLProver` with a storage layer implementation complying with the interface `VersionedAVLStorage`. The `PersistentBatchAVLProver` is able to rollback to a previous version of the tree by [relying on the analogous capability of the `VersionedAVLStorage` implementation](https://github.com/input-output-hk/scrypto/blob/2.0.3/src/main/scala/scorex/crypto/authds/avltree/batch/PersistentBatchAVLProver.scala#L31-L32). The persisted prover `PersistentBatchAVLProver` is [unit tested](https://github.com/input-output-hk/scrypto/blob/2.0.3/src/test/scala/scorex/crypto/authds/avltree/batch/AVLBatchSpecification.scala#L518-L545).
The only storage layer implemented in [the Scala library repo](https://github.com/input-output-hk/scrypto/tree/2.0.3) is the one used for unit tests, named `VersionedAVLStorageMock`: it is an in-memory storage, that [keeps track of the tree root node after *each* proof production](https://github.com/input-output-hk/scrypto/blob/2.0.3/src/test/scala/scorex/crypto/authds/avltree/batch/VersionedAVLStorageMock.scala#L41) so that [the prover can be rolled back](https://github.com/input-output-hk/scrypto/blob/2.0.3/src/main/scala/scorex/crypto/authds/avltree/batch/PersistentBatchAVLProver.scala#L33) to [that version](https://github.com/input-output-hk/scrypto/blob/2.0.3/src/test/scala/scorex/crypto/authds/avltree/batch/VersionedAVLStorageMock.scala#L22), by relying on the garbage collector of the Java VM.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/story/show/152483792
