### ISSUE TITLE
Describe and implement the gossip algorithm for sending out blocks

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#35]

**Comment by cytadela8** [comment]
Nearly ready code is on aeternity/testnet#297

**Comment by cytadela8** [comment]
This is blocked by APIs and Blocks implementation

**Comment by uwiger** [comment]
Current protocol implemented in PR #239 

### Ping
Ping is (currently manually) initiated using `aec_sync:connect_peer(PeerUri)`

The pinging node creates a 'Ping' object, consisting of:
* The genesis block hash ("genesis_hash")
* The hash of the best block ("best_hash")
* Total difficulty ("difficulty")
* Own peer uri ("source")
* Number of peers to share ("share")
* List of known peers ("peers") - preferably excluding the peer in the current dialog

The pinged peer generates its own 'Ping' object, and returns it; both sides compare the two:
1. If the genesis block hashes do not match, abort
2. If the best hashes match, the nodes are in sync
3. Otherwise, compare total difficulty; the node with higher difficulty doesn't need to initiate sync
4. If not higher total difficulty, initiate sync

### Chain Sync
1. Request the header of top (best) block, using a `"top"` HTTP GET request.
2. If the header exists on our chain, check if the corresponding block does as well.
3. If the block is not on the chain, fetch it, using a `"block-by-hash"` HTTP GET request.
4. Fetch the previous block (identified by `prev_hash`), again using `"block-by-hash"`
5. If `height==0`, we've come to the genesis block
6. In reverse order, attempt to write headers and blocks to the chain
7. If a header cannot be inserted, continue if the header already existed on the chain, otherwise abort
8. If a block cannot be written, continue if it already exists on the chain, otherwise abort

### Block broadcast
1. When a (locally mined) block has been written onto the chain, `sync` is notified.
2. `Sync` stores a copy of the block in a cache, and retrieves all known peers in random order.
3. A broadcast request for each peer is queued in a worker pool.
4. For each peer, the block is sent using a `"block"` HTTP POST request.
5. Once all jobs have completed, the block is removed from the cache.

### Block re-broadcast
When a block is received from another peer (via a `"block"` HTTP POST request),
1. If we already have the block, we do not re-broadcast.
2. If the block could be inserted onto our chain, we pass it to `sync` for re-broadcast.
3. The block is broadcast to all (randomly ordered) peers, as above.

**Comment by uwiger** [comment]
Moved description to wiki: https://github.com/aeternity/epoch/wiki/Block-Synch
