### ISSUE TITLE
Problem syncing testnet

### ISSUE THREAD

**Issue by cytadela8** [aeternity/epoch#475]
I tried today to start the testnet following [this tutorial](https://medium.com/@TwenteMining/aeternity-testnet-deployment-68fa218beb07). Only difference is I'm running it on Arch so I started from "Getting the files".

Testnet starts successfully, but about two minutes later crashes while syncing.
[crash.log](https://github.com/aeternity/epoch/files/1540829/crash.log)
[epoch.log](https://github.com/aeternity/epoch/files/1540827/epoch.log)

I tried to get it running twice. Both times from a clear state. (both times unpacked provided .tar.gz to a clean folder) Second time I made sure to not to interact with the node at all while it was syncing. (no requests, no other interaction) I just started it and observer log files. As seen in the log it crashed about two minutes after start.

**Comment by happi** [comment]
Thanks for the error report.

There is a problem in the current release dealing with (other) nodes behind a firewall which leads to epoch needing more file descriptors.

You can increase the limit on file descriptors by editing
/etc/systemd/system.conf
See
https://wiki.archlinux.org/index.php/Limits.conf#nofile

We plan for a bug fix release later today (Friday Dec 8) which will mitigate the problem of needing many file descriptors.
Note that since epoch will gossip with other epoch nodes it will usually need more file descriptors than the system default will allow anyway so increasing the ulimt for file descriptors will likely be needed even after the fix.
