### ISSUE TITLE
Implement SHA256 PoW

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#6]
We can start with the SHA256 [PoW](https://en.bitcoin.it/wiki/Proof_of_work) in case there are delays with the implementation of the [Cuckoo Cycle PoW](5).

**Comment by jborseth** [comment]
Great to have you on the project and seeing progress on AE!

Using SHA256 as a backup PoW is likely dangerous because it creates the opportunity for the existing SHA256 hashing power from the BTC & BCH networks to be pointed at the AE network, causing either inadvertent disruption as miner's come and go quickly switching between networks with highest mining ROI at the moment (such as caused BCH's recent issues) or even creating the opportunity for intentional disruption to the AE network by others. From an adversarial standpoint, it would be safer for AE to use a different hashing function than existing blockchains.

**Comment by wagerlabs** [comment]
@jborseth This would be a development-only stop-gap measure. The last version of the blockchain used SHA256 so we can either reuse or quickly rewrite that code. I don't know how long Cuckoo is gonna take to implement and don't want development to be at a standstill while Cuckoo is being developed.
