### ISSUE TITLE
Check that each block has no more than one coinbase transaction

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#60]

**Comment by cytadela8** [comment]
I think this will just be a part of validation. There is no way to do the check inside coinbase tx code, becouse it doesn't have access to other transactions, just to the trees. We can force coinbase_tx easly to appear only as the first transaction in the block in block validation code. (#17)

(Unimportant note: Analysis made, because I was considering if I can maybe solve this issue now)
