### ISSUE TITLE
Consider variable-length addresses with forward error correcting code

### ISSUE THREAD

**Issue by dmgr** [aeternity/epoch#645]
There are two ideas:
1. One is to have a more convenient address format which will have encoded error correcting code.
2. The other idea is to have a variable length addresses.

## Ad. 1.
Inspiration:
- https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
- https://gitlab.com/tezos/tezos/issues/8
- https://rusty.ozlabs.org/?p=578

## Ad. 2.
Someone could even have an address that will be like 6 letters long and still secure. For example Lisk has 2 times shorter (in terms of bits) addresses than Bitcoin or Ethereum. Someone can say that shorter addresses are less secure due to higher chances of collision with public keys and that is true. The way to secure Lisk address is just to send some funds from that address. This way the public key is revealed in a blockchain and despite the address is short, it is secured by public key now and only the corresponding private key can spend the funds. Someone can say that revealing public key is another risk (that is frequently happening in Ethereum due to common address reuse), but it is up to the user to use a short address secured by revealed public key or a long address. This might have a network effect as many people may race to secure short addresses. They will have to generate a short address and secure it with public key by paying a network fee. To do that they will need to have AE tokens in advance. Unfortunately this will not create a market as selling such a "simple address" is pointless if two parties will hold a private key (unless there will be a way to convert it to a contract address). However it may be possible with a contract address as its owner can be securely changed and such a contract should be upgradable to let the owner to change the contract logic.
As Aeternity is going to have built-in NS service it is not so important feature, but something to consider.

**Comment by knarz** [comment]
I was not aware that BIP-0173 moved out of the draft phase, thank you for pointing that out. We just moved to base58check, so I'm a bit hesitant to come with the next change right away but I'm definitely going to put it onto the roadmap.

I'm not a fan of requiring users to have to claim something in order to receive transactions.

Not revealing the public key is problematic with an account based system and should really only be a problem once our elliptic curve crypto gets broken at which point we are out of luck anyway if we haven't managed to migrate to something else.
