### ISSUE TITLE
Add new transactions to block while mining

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#68]
- Periodically add transactions from the mempool while mining.
- Use a governance variable to decide how often to pick up transactions.

**Comment by zp-sd** [comment]
As agreed with @sennui this should be driven by a system variable (e.g. `sys.config`) instead of governance variable. This depends only on how a miner wants to utilize a node, and may be adjusted individually.

**Comment by zp-sd** [comment]
Actually approach that is currently implemented always recreates new block for mining every 10 attempts. https://github.com/aeternity/epoch/pull/272 changes that, so adding new transactions from pool is configurable in `sys.config`.

One enhancement that is remaining is to avoid rebuilding a block candidate by applying all transactions again when new transactions are spotted in the mempool. Instead of doing that only newly absorbed transaction should be applied to currently mined block candidate, and mining should be resumed.

**Comment by wagerlabs** [comment]
https://www.pivotaltracker.com/story/show/152484006
