### ISSUE TITLE
Build the state of the world

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#70]
- Build the state merkle trees and account balances by processing the blockchain from genesis block.

**Comment by sennui** [comment]
there is also yet another case: merkle tree "checkpoints". If we are to revert a block, because we get longer chain block (say we are +1 to prev-world and we get two new blocks or a block with higher difficulty). Now, we would have to recompute a state tree from the genesis. I wonder, if actually the state tree could be only an "engine" to compute proofs - but a state itself of the world itself would be an array of proofs. That way, it would be easy to revert to "state" to previous block state.

**Comment by wagerlabs** [comment]
+1

**Comment by sennui** [comment]
Do not close this ticket until handling state of the world if fixed after accepting longer fork

We need to force state from the common ancestor and then apply new transactions in regular way

Consult with @lucafavatella where is the longer fork handling in chain service

**Comment by sennui** [comment]
Further work that is not in scope of the Sprint 1
 - handle forcing trees from chain service
 - improve validation from height to comparing hashes
 - adjust caching layer (future pesistance layer) in chain service
   to use trees from blocks as checkpoints 

CC: @wagerlabs @lucafavatella
