### ISSUE TITLE
Allow sending unique ids with each message that will be returned in the response

### ISSUE THREAD

**Issue by devsnd** [aeternity/epoch#708]
## Description of the problem

Let's say I'm registering two oracles to the node. The node will then send two messages back to acknowlege the registration of the oracles. Currently I cannot know for sure that these responses are sent back in the same order as I requested the registration.

Currently, as a workaround, I will only register one oracle at a time and wait for the response that the registration succeeded before sending the next registration request.

Proposal:

It would be nice to be able to send a unique id with each message, which is returned with the respective response from the node. That allows me to easily identify which response belongs to which request. This simple change would make the communication between node and any clients much more robust and easier to implement. (Note: This is by the way the way the websocket framework django-channels handles this problem)

**Comment by hanssv** [comment]
Sounds like a good enhancement - I'll add an improvement ticket for this.

But since we know it is good practice to be able to identify the response from a websocket the in this case the response *already* does contain the oracle ID (which is the same as the account except the hash prefix "ok$" <-> "ak$") so it should not be a problem telling them apart?

Side note: At the moment the websocket success response only says the transaction entered the mempool not that it passed all checks etc...

**Comment by devsnd** [comment]
Yes, it's true that I can use the `oracle_id` to find out where the message belongs (for this specific message type). I'll use that as a slightly better workaround for now.

But still the Demultiplexing of the messages is quite hairy, so thanks for accepting my proposal, this change will make creating the dev-tools much easier!

**Comment by hanssv** [comment]
Tracked in: https://www.pivotaltracker.com/story/show/155060668

All websocket requests (except subscribe? where one or two invocations of exactly the same thing has the same result) should have a unique enough responses but this would be a simplification.

**Comment by hanssv** [comment]
#787

**Comment by hanssv** [comment]
Merged in #787
