### ISSUE TITLE
Update state of the world when receiving blocks

### ISSUE THREAD

**Issue by wagerlabs** [aeternity/epoch#71]
- Block needs to be validated. 
- Transactions in the new block need to update account balances
- and be deleted from the mempool.

**Comment by sennui** [comment]
This ticket is about "state = consensus manager" subsystem.

When this subsystem gets new block from sync subsystem which is networking, it should validate incoming data (if its not malicious, etc).

When data is correct, it has another role besides validation layer - it should force the correct consensus on our node.

It should send data to blockchain service, to state service and to mempool

**Comment by lucafavatella** [comment]
> Block needs to be validated.

I understand this ticket depends on validation of block header i.e. #44

**Comment by lucafavatella** [comment]
> Block needs to be validated.

As an optimization, a set of observed invalid/bad blocks can be kept in order not to waste network and computation resources re-downloading the block. Keeping a set of the hashes of the block headers of the invalid/bad blocks would be sufficient. The set could be limited in size e.g. only the 100 most recently seen on the network.

The typical case I have in mind is a block whose header is valid but whose body is not. This can happen if e.g. any of the following happens:
* Any of the transactions in block is structurally invalid e.g. invalid signature;
* Any of the transactions in the block shall not have been included (or not included in that position) because of unfulfilled requirements/assumptions (e.g. account balance not sufficient, nonce not big enough, oracle creation with id already used);
* Hash of the root of the state trees after application of transactions is not correct (consider that, provided transactions are executed in order from genesis, the hash of the root is deterministic and verifiable).

**Comment by sennui** [comment]
@lucafavatella great idea about the bad blocks! Yes, please include them (hashes).

And Yes it depends on #44 and on validating the block itself. @lucafavatella do you think we should move validation to your service and keep this one only as a dispatcher of requests? (we need central place to control business flow of incoming new block anyway). 

Probably the validation code should live in a block service but be executed based on call from here.
It will be like a dependency path - when one check is green, we can proceed to the next one with new block handling

**Comment by lucafavatella** [comment]
> @lucafavatella do you think we should move validation to your service and keep this one only as a dispatcher of requests? (we need central place to control business flow of incoming new block anyway).
> 
> Probably the validation code should live in a block service but be executed based on call from here.
> It will be like a dependency path - when one check is green, we can proceed to the next one with new block handling

@sennui Block validation takes time and I would not make it run in a server holding state (like the one in #69) as that would become a bottleneck. I believe validation can be run by any process, interacting with the other services as needed.

**Comment by sennui** [comment]
@lucafavatella true, but I meant logic not the context. The operation will be run in a context of dispatcher (#71) or dispartcher-spawned process. The code should live in #69 and be written by you or Zbig because you know the most about it @zp-sd
