### ISSUE TITLE
Sending a transaction when the balance is low should fail

### ISSUE THREAD

**Issue by wiseye** [aeternity/epoch#837]
## Expected Behavior
When send the TestAE to an address which no transaction has taken place, the transaction should fail, not suspending.

## Actual Behavior
1. Check Balance
curl -G 'http://127.0.0.1:3103/v2/account/balance/ak$3QZsDX6J9YL6eJXEAoKMDBv86HXhCDzYDS1gBqz5MswBXSCWCyQtQikxadaWAXZwAYXCb6hEtVm3c61wBHoAdYEwZLoN6S'
{"reason":"Account not found"}
2. Send 2 with fee 1 to another address (Official example address)
3. Tomorrow, trans 20 to this address(ak$3QZsDX6J9YL6eJXEAoKMDBv86HXhCDzYDS1gBqz5MswBXSCWCyQtQikxadaWAXZwAYXCb6hEtVm3c61wBHoAdYEwZLoN6S)
4. Both transactions were confirmed at the same time(same block height).

## Steps to Reproduce the Problem

  1. Gen a new address.
  2. Send to another address.
  3. Wait a long time(a few hours)
  4. Send to this new address from another(The amount to be sent later needs to be larger than the previous one.)
  5. Both transactions will be confirmed at the same time(same block height).
  
## Logs, error output, etc.
  Our test block height 1757
  https://explorer.aepps.com/#/block/1757
  The second sending transaction(Send 2 with fee 1) is a transaction created yesterday.

**Comment by velzevur** [comment]
@wiseye thank you for the detailed report.

Currently this is by design. The reasoning is the following:
Alice makes a valid transaction and sends some tokens to Bob. Alice might have enough tokens for that but she might not.

* If she does - a miner will include her transaction in a block.

* If she doesn't have enough tokens to spend, the transaction stays in the mempool of transactions and waits for Alice balance to get updated. Once she has enough tokens to spend - a miner will include her transaction in a block and Bob receives his tokens.

A properly signed transaction from Alice will stay in a miner's mempool as long as the miner considers it is practial. There will be a mechanism for a miner dropping transactions on a certain criteria but it is not around yet so those pending transactions stay in the mempool until they're resolved.

If Alice doesn't want for a transaction to be executed - she shouldn't post it in the first place.

**Comment by wiseye** [comment]
@velzevur Well, this means that you may add timeout mechanisms or other drop mechanisms in the future. Thank you!
